#!/bin/bash
# Do not make this executable!
# use a . .command to invoke perhaps with an alias like enved

if [ "$0" = "$BASH_SOURCE" -o -z "$1" ]
then
  echo Error. You must source this script
  echo Usage: . envedit2 VAR
  echo '  or   . envedit2 alias [alias]'
  echo E.g.: . $0 PATH
  exit 1
fi

if [ "$1" = "alias" ]
then
  alias ${2:-enved}=". $BASH_SOURCE"
  alias ${2:-enved}
else

ENVEDIT_V=`printf '%q' ${!1}`
ENVEDIT_TMP=$(echo \"\\e[0n\": \"$1=\\\"${ENVEDIT_V}\\\"\")
bind "$ENVEDIT_TMP" ; ((sleep 0.05; printf '\e[5n') & )
fi
