#!/bin/bash
# Do not make this executable!
# use a . .command to invoke perhaps with an alias like enved

usage() {
  echo Usage: . ${BASH_SOURCE[0]} VAR
  echo "  or   . ${BASH_SOURCE[0]} alias [alias]"
  echo E.g.: . ${BASH_SOURCE[0]} PATH
}

if [ "$0" = "${BASH_SOURCE[0]}" ]
then
  echo Error. You must source this script
  usage
  exit 1
fi

if [ -z "$1" ]
then
  usage
  exit 1
fi

if [ "$1" = "alias" ]
then
  alias ${2:-enved}=". `realpath ${BASH_SOURCE[0]}`"
  alias ${2:-enved}
else

# set device OK status report to be our edit string (ESC[0n is the response to ESC[5n command)
ENVEDIT_V=`printf '%q' ${!1}`
ENVEDIT_TMP="`echo \"\\e[0n\": \"$1=\\\"${ENVEDIT_V}\\\"\"`"
bind "${ENVEDIT_TMP}" ; ((sleep 0.05; printf '\e[5n') & )
fi
